fixed ould not configure AzureCli Authorizer

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,6 +7,10 @@ on:
 env:
   NODE_VERSION: 16
 
+permissions:
+  contents: read
+  id-token: write
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -28,6 +32,9 @@ jobs:
 
       - name: 🛠️ Set up Terraform
         uses: hashicorp/setup-terraform@v3
+        with:
+            terraform_version: 1.5.0
+
 
       - name: 📦 Terraform Init
         run: terraform -chdir=infra init
@@ -43,6 +50,20 @@ jobs:
           echo "DB_USER=$(echo $json | jq -r '.mysql_admin_user.value')" >> $GITHUB_ENV
           echo "DB_PASS=$(echo $json | jq -r '.mysql_admin_pwd.value')" >> $GITHUB_ENV
           echo "DB_NAME=$(echo $json | jq -r '.mysql_database_name.value')" >> $GITHUB_ENV
+
+      - name: ✅ Validate Terraform Outputs
+        run: |
+            if [ -z "$DB_HOST" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASS" ] || [ -z "$DB_NAME" ]; then
+            echo "❌ One or more Terraform outputs are missing"
+            exit 1
+            fi
+
+      - name: 🔐 Check SSH key presence
+        run: |
+            if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
+            echo "❌ SSH key is missing"
+            exit 1
+            fi
 
       - name: 🔑 Configure SSH
         run: |
